apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: guestbook-ui
  type: NodePort
